---
- author: BunsenLabs
  base: hydrogen2
  source: https://www.bunsenlabs.org
- author: BunsenLabs
  base: BunsenMarch2016
  source: https://www.bunsenlabs.org
- author: atropos
  source: https://forums.bunsenlabs.org/viewtopic.php?pid=12511#p12511
- author: BunsenLabs
  base: default
  source: https://www.bunsenlabs.org
- author: yunn
  source: https://forums.bunsenlabs.org/viewtopic.php?pid=24254#p24254
- author: djzk
  base: djzk2
  source: https://forums.bunsenlabs.org/viewtopic.php?pid=20740#p20740
- author: fog
- author: damo
- author: hhh
- author: ututo
  source: https://forums.bunsenlabs.org/viewtopic.php?pid=24318#p24318
- author: djzk
  base: djzk3
  source: https://forums.bunsenlabs.org/viewtopic.php?pid=21136#p21136
- author: Sector11
  base: s11
- author: Dobbie03
- author: hhh
  base: hydrogenteal1
- author: hhh
  base: hhh2
- author: panda
